flowchart LR
subgraph Your Backend
B1[User_1 Profile]
B2[User_1 Profile]
B3[User_2 Profile]
end

QP{Hicon Query Proxy}

subgraph Hicon Query Proxy
direction TB
combine[Combine Identical Queries]
execute[Execute Single Identical Queries]
end

DB[(Redis\nor SQL Database...)]
B1 & B2 -->|grpc| QP
B3 -->|grpc| QP
QP -->|Analyze Queries| combine
combine --> execute
execute <-->|User_1 Profile| DB
execute <-->|User_2 Profile| DB
execute -->|Shared Result| B1
execute -->|Shared Result| B2
execute -->|Separate Result| B3
