// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: hicon-sm/sql_executor.proto

package sqlexecutor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hicon_sm_sql_executor_proto protoreflect.FileDescriptor

const file_hicon_sm_sql_executor_proto_rawDesc = "" +
	"\n" +
	"\x1bhicon-sm/sql_executor.proto\x1a\x19google/protobuf/any.proto2\x9d\x05\n" +
	"\vSQLExecutor\x12<\n" +
	"\fUpsertConfig\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x128\n" +
	"\bFindByPK\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x127\n" +
	"\aFindOne\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x127\n" +
	"\aFindAll\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x124\n" +
	"\x04Exec\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x12:\n" +
	"\n" +
	"BulkInsert\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x12:\n" +
	"\n" +
	"UpdateByPK\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x129\n" +
	"\tUpdateAll\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x12>\n" +
	"\x0eBulkUpdateByPK\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x12:\n" +
	"\n" +
	"DeleteByPK\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x12?\n" +
	"\x0fBulkWriteWithTx\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00B\x0fZ\r./sqlexecutorb\x06proto3"

var file_hicon_sm_sql_executor_proto_goTypes = []any{
	(*anypb.Any)(nil), // 0: google.protobuf.Any
}
var file_hicon_sm_sql_executor_proto_depIdxs = []int32{
	0,  // 0: SQLExecutor.UpsertConfig:input_type -> google.protobuf.Any
	0,  // 1: SQLExecutor.FindByPK:input_type -> google.protobuf.Any
	0,  // 2: SQLExecutor.FindOne:input_type -> google.protobuf.Any
	0,  // 3: SQLExecutor.FindAll:input_type -> google.protobuf.Any
	0,  // 4: SQLExecutor.Exec:input_type -> google.protobuf.Any
	0,  // 5: SQLExecutor.BulkInsert:input_type -> google.protobuf.Any
	0,  // 6: SQLExecutor.UpdateByPK:input_type -> google.protobuf.Any
	0,  // 7: SQLExecutor.UpdateAll:input_type -> google.protobuf.Any
	0,  // 8: SQLExecutor.BulkUpdateByPK:input_type -> google.protobuf.Any
	0,  // 9: SQLExecutor.DeleteByPK:input_type -> google.protobuf.Any
	0,  // 10: SQLExecutor.BulkWriteWithTx:input_type -> google.protobuf.Any
	0,  // 11: SQLExecutor.UpsertConfig:output_type -> google.protobuf.Any
	0,  // 12: SQLExecutor.FindByPK:output_type -> google.protobuf.Any
	0,  // 13: SQLExecutor.FindOne:output_type -> google.protobuf.Any
	0,  // 14: SQLExecutor.FindAll:output_type -> google.protobuf.Any
	0,  // 15: SQLExecutor.Exec:output_type -> google.protobuf.Any
	0,  // 16: SQLExecutor.BulkInsert:output_type -> google.protobuf.Any
	0,  // 17: SQLExecutor.UpdateByPK:output_type -> google.protobuf.Any
	0,  // 18: SQLExecutor.UpdateAll:output_type -> google.protobuf.Any
	0,  // 19: SQLExecutor.BulkUpdateByPK:output_type -> google.protobuf.Any
	0,  // 20: SQLExecutor.DeleteByPK:output_type -> google.protobuf.Any
	0,  // 21: SQLExecutor.BulkWriteWithTx:output_type -> google.protobuf.Any
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_hicon_sm_sql_executor_proto_init() }
func file_hicon_sm_sql_executor_proto_init() {
	if File_hicon_sm_sql_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hicon_sm_sql_executor_proto_rawDesc), len(file_hicon_sm_sql_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hicon_sm_sql_executor_proto_goTypes,
		DependencyIndexes: file_hicon_sm_sql_executor_proto_depIdxs,
	}.Build()
	File_hicon_sm_sql_executor_proto = out.File
	file_hicon_sm_sql_executor_proto_goTypes = nil
	file_hicon_sm_sql_executor_proto_depIdxs = nil
}
